import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { graphql } from "~/generated/graphql";
import { useQuery } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

const REPORTS_QUERY = graphql(/* GraphQL */ `
  query GetStores {
    stores {
      exampleField
    }
  }
`);

export default function Home() {
  const { data } = useQuery(REPORTS_QUERY);

  console.log({ data: data });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <pre>{JSON.stringify(data?.stores[0], null, 2)}</pre>
      </main>
    </>
  );
}
